name: Angular deployment
on:
  push:
    branches:  ["dev-lgs"]
       
jobs:
  deploy-dev-lgs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev-lgs'
    steps:
      - name: Ver por consola variables de entorno
        run: |
            echo "Home: ${HOME}"
            echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
            echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
            echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
            echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
            echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
            echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
            echo "GITHUB_SHA: ${GITHUB_SHA}"
            echo "GITHUB_REF: ${GITHUB_REF}"

      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - name: npm configuration
        run: npm config set legacy-peer-deps true

      - name: Install dependencies
        run: npm ci
    
      - name: Build
        run: npm run build:dev-lgs

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.SUBDEV_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SUBDEV_KNOWN_HOSTS }}

      - name: Deploy using rsync
        run: rsync -avz ./dist/cuba/ ${{ secrets.SUBDEV_SSH_USER }}@${{ secrets.SUBDEV_SSH_HOST }}:/var/www/lgs
      
      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs
